## Testing

In [2]:
import numpy as np 
import pandas as pd
import torch
import torch.nn as nn
import skimage
import skimage.io

In [8]:
img = 'C:/Users/cathx/repos/argoverse-api/train/6f153f9c-edc5-389f-ac6f-40705c30d97e/ring_front_center/ring_front_center_315966434214396776.jpg'

In [10]:
arr = (skimage.io.imread(img).astype('float32'))

In [11]:
arr.shape

(1200, 1920, 3)

In [9]:
slice_a = np.array([[[1, 1, 1],
                  [1, 1, 1],
                  [1, 1, 1]],
                  [[1, 1, 1],
                  [1, 1, 1],
                  [1, 1, 1]]])

slice_a.shape

(2, 3, 3)

In [14]:
W = np.array([[[1, 1, 1],
                  [1, 1, 1],
                  [1, 1, 1]],
                  [[1, 1, 1],
                  [1, 1, 1],
                  [1, 1, 1]]])

In [15]:
W.shape

(2, 3, 3)

In [16]:
Z = np.dot(slice_a, W)

In [17]:
Z.shape


(2, 3, 2, 3)

In [33]:
np.random.seed(1)
a_slice_prev = np.random.randn(4, 4, 3)
W = np.random.randn(4, 4, 3)

In [34]:
a_slice_prev.shape

(4, 4, 3)

In [35]:
W.shape

(4, 4, 3)

In [36]:
s = np.dot(a_slice_prev.T, W)

In [37]:
Z = np.sum(s)

In [38]:
Z

-38.8067171014885

In [41]:
np.float64(Z) + np.float64(np.array([[1], [1], [1]]))

array([[-37.8067171],
       [-37.8067171],
       [-37.8067171]])

In [42]:
b = np.array([[1], [1], [1]])

In [43]:
b = np.float64(b)

In [44]:
b

array([[1.],
       [1.],
       [1.]])

In [45]:
b = np.random.randn(1, 1, 1)

In [46]:
b.shape

(1, 1, 1)

In [47]:
b

array([[[-0.34385368]]])

In [63]:
def zero_pad(X, pad):
    """
    Pad with zeros all images of the dataset X. The padding is applied to the height and width of an image, 
    as illustrated in Figure 1.
    
    Argument:
    X -- python numpy array of shape (m, n_H, n_W, n_C) representing a batch of m images
    pad -- integer, amount of padding around each image on vertical and horizontal dimensions
    
    Returns:
    X_pad -- padded image of shape (m, n_H + 2 * pad, n_W + 2 * pad, n_C)
    """
    
    #(≈ 1 line)
    X_pad = np.pad(X, ((0,0),(pad, pad),(pad,pad),(0,0)), mode='constant', constant_values=(0,0))
    # YOUR CODE STARTS HERE
    
    
    # YOUR CODE ENDS HERE
    
    return X_pad

In [58]:
A_prev = np.random.randn(2, 5, 7, 4)
W = np.random.randn(3, 3, 4, 8)
b = np.random.randn(1, 1, 1, 8)
hparameters = {"pad" : 1,
               "stride": 2}

In [59]:
(m, n_H_prev, n_W_prev, n_C_prev) = A_prev.shape

(f, f, n_C_prev, n_C) = W.shape

stride = hparameters['stride']
pad = hparameters['pad']

n_H = int(n_H_prev - (f+2*pad)/stride) + 1
n_W = int(n_W_prev - (f+2*pad)/stride) + 1

In [79]:
Z = np.zeros([m, n_H, n_W, n_C])
Z.shape

(2, 3, 5, 8)

In [80]:
Z

array([[[[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
 

In [64]:
A_prev_pad = zero_pad(A_prev, pad)

In [66]:
A_prev_pad.shape

(2, 7, 9, 4)

In [85]:
A_prev_pad[0].shape

(7, 9, 4)

In [86]:
a_slice_prev = A_prev_pad[0][0:3, 0:3, 0,]
a_slice_prev.shape

(3, 3)

In [87]:
for i in range(m):               # loop over the batch of training examples
        a_prev_pad = A_prev_pad[i]               # Select ith training example's padded activation
        print(a_prev_pad.shape)
        for h in range(n_H):           # loop over vertical axis of the output volume
            # Find the vertical start and end of the current "slice" (≈2 lines)
            vert_start = h
            vert_end = vert_start + f
            
            for w in range(n_W):       # loop over horizontal axis of the output volume
                # Find the horizontal start and end of the current "slice" (≈2 lines)
                horiz_start = w
                horiz_end = horiz_start + f
                
                for c in range(n_C):   # loop over channels (= #filters) of the output volume
                                        
                    # Use the corners to define the (3D) slice of a_prev_pad (See Hint above the cell). (≈1 line)
                    a_slice_prev = a_prev_pad[vert_start:vert_end, horiz_start:horiz_end, :n_C_prev]
                    print(a_slice_prev.shape)
                    # Convolve the (3D) slice with the correct filter W and bias b, to get back one output neuron. (≈3 line)
                    weights = W[:, :, :, c]
                    print('weights shape:', weights.shape)
                    biases = b[:,:,:,c]
                    print('biases_shape:', biases.shape)
#                     print('biases', biases)
                    print('a_slice_prev shape:', a_slice_prev.shape)
                    print('dot+prod_shape:', (np.dot(a_slice_prev.T, weights)).shape)
        
                    num = np.dot(a_slice_prev.T, weights) + biases
                    print('num:', num)
                    print('num_shape,', num.shape)
                    Z[i, h, w, c] = np.dot(a_slice_prev.T, weights) + biases
    # YOUR CODE STARTS HERE
    
    
    # YOUR CODE ENDS HERE
    
    # Save information in "cache" for the backprop
cache = (A_prev, W, b, hparameters)
    
#    return Z, cache

(7, 9, 4)
(3, 3, 4)
weights shape: (3, 3, 4)
biases_shape: (1, 1, 1)
a_slice_prev shape: (3, 3, 4)
dot+prod_shape: (4, 3, 3, 4)
num: [[[[-0.72835009 -0.72835009 -0.72835009 -0.72835009]
   [-0.72835009 -0.72835009 -0.72835009 -0.72835009]
   [-0.72835009 -0.72835009 -0.72835009 -0.72835009]]

  [[-2.75997531  1.63620818 -3.60453142  1.31114501]
   [-0.84084772 -0.84633656 -0.76188764 -0.69320778]
   [ 0.81520533 -1.17041176 -0.63777133 -0.0768057 ]]

  [[-0.7632265  -0.70504778 -0.69823777 -0.74182232]
   [-0.73684576 -0.66473326 -0.73476476 -0.71963922]
   [-0.65993385 -0.74979246 -0.6997811  -0.73866135]]]


 [[[-0.72835009 -0.72835009 -0.72835009 -0.72835009]
   [-0.72835009 -0.72835009 -0.72835009 -0.72835009]
   [-0.72835009 -0.72835009 -0.72835009 -0.72835009]]

  [[-0.44037289 -1.45861637  1.49576566 -2.12538601]
   [-0.86241369  0.78842125 -0.85702691 -0.54805804]
   [ 0.01076777 -0.98226953 -0.12386864 -1.31193183]]

  [[ 1.26813351 -2.54592228 -0.22860613 -1.31338571]
   [-0.

ValueError: setting an array element with a sequence.

In [78]:
(np.dot(weights.T, a_slice_prev) + biases).shape

(4, 3, 3, 4)

In [88]:
import tensorflow as tf

In [90]:
tf.random.set_seed(10)
box_confidence = tf.random.normal([19, 19, 5, 1], mean=1, stddev=4, seed = 1)
boxes = tf.random.normal([19, 19, 5, 4], mean=1, stddev=4, seed = 1)
box_class_probs = tf.random.normal([19, 19, 5, 80], mean=1, stddev=4, seed = 1)

In [92]:
# get the boxes confidence
bscores = box_confidence * box_class_probs
# bscores[:10]
bscores.shape

TensorShape([19, 19, 5, 80])

In [107]:
maxes = tf.keras.backend.argmax(bscores, axis = -1)
maxes[0]

<tf.Tensor: shape=(19, 5), dtype=int64, numpy=
array([[20, 74,  8, 67, 56],
       [54, 35,  5, 34, 67],
       [15,  9,  3, 51, 35],
       [ 9, 21, 63, 59,  3],
       [ 9, 65, 33, 73, 15],
       [57,  6, 61,  0, 35],
       [44, 41, 40, 56, 45],
       [52, 17, 47, 65, 61],
       [58,  2,  3,  6, 18],
       [ 7, 63, 76, 37, 59],
       [19, 72, 49,  8, 19],
       [ 3, 43, 19,  9, 65],
       [72, 60, 49, 64,  5],
       [24, 35, 36, 49, 68],
       [54, 45, 23, 59, 49],
       [61, 60,  6, 28, 29],
       [ 2, 68, 59, 11, 48],
       [18, 37, 70, 21, 77],
       [20, 17, 48, 61,  1]], dtype=int64)>

In [108]:
maxes.shape

TensorShape([19, 19, 5])

In [106]:
max_cls = tf.keras.backend.max(bscores, axis = -1)
max_cls[0]

<tf.Tensor: shape=(19, 5), dtype=float32, numpy=
array([[  7.8824973,  15.941692 ,   9.270486 ,  10.659197 ,  11.924357 ],
       [ 90.77388  ,   5.974023 ,   1.8933523,  29.829315 ,  31.208069 ],
       [  6.537015 ,  41.7416   ,  23.049517 ,  37.349552 ,  13.52168  ],
       [ 35.152668 ,  25.007286 ,   6.500367 ,  10.509995 ,  18.339254 ],
       [ 41.723614 ,  28.937899 ,  17.628412 ,   8.391325 ,  34.849873 ],
       [  3.5203695,  15.2743435,  91.54565  ,   6.2122216,  39.827873 ],
       [ 81.324005 ,  36.825172 ,  49.645226 ,  34.83155  ,  73.848755 ],
       [ 24.521795 ,  34.16109  ,  27.373856 ,  12.873953 ,   8.508822 ],
       [ 24.48026  ,  12.10325  ,  15.390799 ,  79.91069  ,  69.83895  ],
       [ 29.635628 ,  12.406755 ,  11.126411 ,  22.408543 ,  39.27029  ],
       [  4.067437 ,  14.570456 ,  23.152266 , 117.5296   ,  12.946864 ],
       [  1.6977274,  12.990867 ,  81.414536 ,  73.43122  ,  27.535694 ],
       [ 17.72237  ,  67.009735 ,  63.402355 ,   8.269994 ,  53

In [109]:
max_cls.shape

TensorShape([19, 19, 5])

In [93]:
# get the max class i.e. the class with the maximum value / confidence
max_cls = tf.math.argmax(bscores, axis=-1)
max_cls.shape
# bcls_scores = boxes[max_cls]

TensorShape([19, 19, 5])

In [96]:
max_cls[10]

<tf.Tensor: shape=(19, 5), dtype=int64, numpy=
array([[38, 40, 76, 59,  7],
       [57,  1, 66, 21, 61],
       [66,  1,  3, 75, 14],
       [77, 67, 34, 38, 28],
       [40, 21, 31, 27, 25],
       [73, 27, 22, 22, 60],
       [67, 23, 25, 13, 17],
       [41, 54, 48,  3, 39],
       [52, 12, 60,  7, 26],
       [38,  0, 49, 25, 30],
       [27, 25, 33, 28, 16],
       [49,  0,  8, 64, 51],
       [36, 36, 17, 27, 25],
       [39, 51, 71, 74,  3],
       [26, 63,  3, 49, 27],
       [73, 66, 62, 64, 20],
       [72, 43, 50, 54, 10],
       [29, 35, 46, 73, 61],
       [40,  2, 54, 37, 77]], dtype=int64)>

In [99]:
bcls_score = boxes[max_cls[-1]]

InvalidArgumentError: Expected begin, end, and strides to be 1D equal size tensors, but got shapes [1,19,5], [1,19,5], and [1] instead. [Op:StridedSlice] name: strided_slice/

In [53]:
b.shape

(1, 1, 1, 8)

In [54]:
b

array([[[[-0.47867236, -0.32905155,  1.34710546, -1.04906775,
           0.3166589 , -1.89526695,  0.08972912,  0.41026575]]]])

In [57]:
b[:,:,:,1]

array([[[-0.32905155]]])