# CodeSignal Level 1

Given a year, return the century it is in. The first century spans from the year 1 up to and including the year 100, the second - from the year 101 up to and including the year 200, etc.

Example

For year = 1905, the output should be
centuryFromYear(year) = 20;
For year = 1700, the output should be
centuryFromYear(year) = 17.

In [2]:
def centuryFromYear(year):
    return (year + 99) // 100


def centuryFromYear(year):
    return math.ceil(year/100)

In [1]:
inputArray = [3, 6, -2, -5, 7, 3]

In [5]:
for i in range(len(inputArray)-1):
    print(inputArray[i])

3
6
-2
-5
7


In [6]:
i = 0
mult = []
# while inputArray:
for i in range(len(inputArray)-1):
    mul = inputArray[i] * inputArray[i+1]
    mult.append(mul)
    
    

In [7]:
mult

[18, -12, 10, -35, 21]

In [8]:
statues = [6, 2, 3, 8]

In [15]:
statues = sorted(statues)
diff = []
for i in range(len(statues)-1):
    minus = statues[i] - statues[i+1]
    diff.append(minus)
    

In [17]:
statues

[2, 3, 6, 8]

In [20]:
diff = [x + 1 for x in diff]

In [21]:
diff

[0, -2, -1]

In [26]:
tots = abs(sum((diff)))

In [27]:
abs(tots)

3

In [29]:
seq = [1, 3, 2, 1]

In [28]:
for i in range(len(seq)-1):
    diff = seq[i] - seq[i-1]
    tots = abs(sum(diff))
    if tots > 1:
        return False
    else:
        return True

SyntaxError: 'return' outside function (<ipython-input-28-734975b57cb0>, line 5)

In [ ]:
i = 0
# while seq:
#     print(i)

In [3]:
import numpy as np

In [27]:
mat = np.array([[0, 1, 1, 2], [0, 5, 0, 0], [2, 0, 3, 3]])

In [84]:
mat = [[0,1,1,2], 
 [0,5,0,0], 
 [2,0,3,3]]

In [88]:
len(mat[1])

4

In [86]:
for i in range(len(mat)):
    for j in range(len(mat[i])):
        if mat[i][j] == 0:
            print(j)

0
0
2
3
1


In [92]:
tots = 0
for i in range(len(mat[0])):
    print(mat[i])
    for j in range(len(mat)):
        if mat[j][i] != 0:
            tots  += mat[j][i]
        # if it issss equal to zero.. we do not follow down the column any more at alll
        # AND moveo onto the next column.
        else:
            break

[0, 1, 1, 2]
[0, 5, 0, 0]
[2, 0, 3, 3]


IndexError: list index out of range

In [90]:
tots

9

In [50]:
mat = np.array(mat)

In [ ]:
indices = np.argwhere(mat[i]==0)

In [75]:
mat = [[0,1,1,2], 
 [0,5,0,0], 
 [2,0,3,3]]

In [82]:
indices = {}
for i in range(len(mat)):
    print(i)
    print(mat[i])
    zero = mat[i].index(0)
    indices[i] = zero
    print("indices 0:", zero)

0
[0, 1, 1, 2]
indices 0: 0
1
[0, 5, 0, 0]
indices 0: 0
2
[2, 0, 3, 3]
indices 0: 1


In [83]:
indices

{0: 0, 1: 0, 2: 1}

In [77]:
# go through the first list and see if it has 0s, save the index value
indices = []
for i in range(len(mat)):
    # got the index in the first array
    zero = mat[i].index(0)
    indices.append(zero)
    # zero the elements in that location
#     mat[i+1] = mat[i][zero]
    
print(zero)
print(mat)

1
[[0, 1, 1, 2], [0, 5, 0, 0], [2, 0, 3, 3]]


In [78]:
indices

[0, 0, 1]

In [53]:
for i in range(len(mat)):
    indices = np.argwhere(mat==0)
    first_sum = sum(mat[0])
    # next if the next array has numbers in the previous 0 location:
    
    j, k = indices

print(indices)
    

[[0 0]
 [1 0]
 [1 2]
 [1 3]
 [2 1]]


In [59]:
indices[1][0]

1

In [61]:
j, k = indices[0]
j, k

(0, 0)

In [44]:
for i in range(len(mat)):
#     print(i)
#     lis = [x == 0 where x ]
    for j in mat[i]:
        if j == 0:
            print(j)
#             print(mat[i])

0
0
0
0
0


In [46]:
tots = sum(mat)
tots

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [20]:
tots = np.where(mat==0)
tots

(array([0, 1, 1, 1, 2], dtype=int64), array([0, 0, 2, 3, 1], dtype=int64))

In [13]:
print(tots)

[2 6 4 5]


In [28]:
zeros = np.argwhere(mat==0)
zeros

array([[0, 0],
       [1, 0],
       [1, 2],
       [1, 3],
       [2, 1]], dtype=int64)

In [32]:
mat[zeros[0][0]]

array([0, 1, 1, 2])

In [25]:
for i in range(len(mat)):
#     print(i)
    for j in mat[i]:
        mat[zeros[0]]

0
1
1
2
0
5
0
0
2
0
3
3


In [11]:
for i in range(len(mat)):
#     print(mat[i])
    for j in range(len(mat[i])):
        if mat[i][j] == 0:
            mat[i+1][j] == 0
            
#             mat.remove(mat[i][j]) 
        
            

IndexError: index 3 is out of bounds for axis 0 with size 3

In [154]:
inputArray = ["aba", "aa", "ad", "vcd", "aba"]

In [98]:
for i in range(len(inputArray)):
    
    print(len(inputArray[i]))

3
2
2
3
3


In [172]:
inputArray = ["a", 
 "abc", 
 "cbd", 
 "zzzzzz", 
 "a", 
 "abcdef", 
 "asasa", 
 "aaaaaa"]

In [177]:
maxes = []
ret = []
maxes.append(inputArray[0])
j = 0
for i in range(1, len(inputArray)):
    print(inputArray[i])
    if len(maxes[j]) > len(inputArray[i]):
#         print(maxes)
        continue
    elif len(maxes[j]) == len(inputArray[i]):
        maxes.append(inputArray[i])
        j += 1
    elif len(maxes[j]) < len(inputArray[i]):
        maxes[j] = inputArray[i]
        # also check if the previous element also has lower length than the next element.
        

abc
cbd
zzzzzz
a
abcdef
asasa
aaaaaa


In [178]:
maxes

['abc', 'zzzzzz', 'abcdef', 'aaaaaa']

In [182]:
res = len(max(inputArray, key = len)) 
res

6

In [184]:
max_len = len(max(inputArray, key=len))
ret = []
for i in range(len(inputArray)):
    if len(inputArray[i]) < max_len:
        continue
    elif len(inputArray[i]) == max_len:
        ret.append(inputArray[i])
        

In [185]:
ret


['zzzzzz', 'abcdef', 'aaaaaa']

In [180]:
arr = []
maxes = []
maxes.append(inputArray[0])
for i in range(len(inputArray)):
    # append first element
    # if the element in visited has greater length than the next item in the original list,
    # move on
    print("Maxes:", maxes)
    next_elm = inputArray[i+1]
    print("next_elm", next_elm)
    if len(maxes[i]) < len(inputArray[i+1]):
        maxes[i] = inputArray[i+1]
    elif len(maxes[i]) == len(inputArray[i+1]):
        maxes.append(inputArray[i+1])
    elif len(maxes[i]) > len(inputArray[i+1]):
        continue
#     for i in range(len(maxes)):
#         print("First i in Maxes:", maxes[i])
#         if len(maxes[i]) < len(inputArray[i+1]):
#             maxes[i] = inputArray[i+1]

#         elif len(maxes[i]) == len(inputArray[i+1]):
#             maxes.append(inputArray[i+1])
#         elif len(maxes[i]) > len(inputArray[i+1]):
#             continue
#         else:
#             continue

#             maxes.replace(maxes[i], inputArray[i+1])
    
            
#     length = len(inputArray[i])
#     maxes.append(length)
#     max_len = max((maxes))
#     arr.append(max(len(inputArray[i])))

Maxes: ['a']
next_elm abc
Maxes: ['abc']
next_elm cbd


IndexError: list index out of range

In [130]:
maxes

['aba']

In [105]:
max_len

3

In [190]:
s1 = 'aabcc'
s2 = 'adcaa'

In [187]:
s.split()

['aabcc']

In [189]:
list(s)

['a', 'a', 'b', 'c', 'c']

In [197]:
one = list(s1)
two = list(s2)
count = 0
for i in two:
#     print(i)
    for j in one:
        if i == j:
            one.remove(i)
            two.remove(j)
            count += 1


In [198]:
count

3

In [200]:
from collections import Counter

In [208]:
dict1 = Counter(s1)
dict2= Counter(s2)

In [209]:
dict1

Counter({'a': 2, 'b': 1, 'c': 2})

In [210]:
common = dict1& dict2

In [213]:
sum(common.values())

3

# Python Set

Python sets are used to store multiple items in a single variable. For example, if we had multiple similar elements, a set would use only one element all the existing elements. And they will be saved in '{' and '}' to represent a set. 

In [225]:
s1 = 'aabcc'
set_1 = set(s1)
set_1

{'a', 'b', 'c'}

In [226]:
for i in set(s1):
    print(i)

b
a
c


In [235]:
test = 'hhjjjlllkkkk'
set_t = set(test)
set_t

{'h', 'j', 'k', 'l'}

In [236]:
for i in set_t:
    print(i)

j
k
h
l


In [237]:
# i in set are 'a', 'b', 'c'
# 
'''
for i in set(s1):
    print('i: {} and s1.count(i): {}'.format(i, s1.count(i)))
    # minimum function decides on the element that happens the minimum number of times between
    # the two strings i.e. if the list a has 2 'a's but the second one has 3 'a's we care about the
    # 2 in the first list. 
    com = min(s1.count(i), s2.count(i))
    print(com)
'''

count = sum(min(s1.count(i), s2.count(i)) for i in set(s1))
count


3

WE convert the first string into a set, getting the elements that exist in the set and conjugating them into one instance so that only if the elements exist in the first string, would we look for them in the second one.
THEN, for the i-th element that exists in the set, we look for the minimum of count in both strings i.e. if the element 'a' exists in string a as shown by the set(s1), we would get the count for that element in both string1 and string2 and get the minimum of both values because we only care about the minimum instance in both elements i..e no overlapping. THEN, we sum up the minimum counts for all the elements and get the counter.

### Another approach



In [247]:
n = 239017

str_n = str(n)
len_n = len(str_n)
print(len_n)
half_n = int(len_n/2) 
half_str = int(str_n[:half_n])

6


In [246]:
int(half_str)

239

In [245]:
int(str_n[half_n:])

17

### Replace Trees Problem

 Using **enumerate()** to work with an array

In [2]:
import numpy as np

In [3]:
a = [-1, 150, 190, 170, -1, -1, 160, 180]
a_t = np.zeros(len(a))
a_t


array([0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
type(a_t)

numpy.ndarray

Get all the elements that are more than 0 and sort them already.
Then, go through the 0s array.
Sort the array skipping the -1.


In [17]:
a = [-1, 150, 190, 170, -1, -1, 160, 180]
for i in range(len(a)-1):
    if a[i] == -1:
        continue
#     if a[i+1] == -1:
#         continue
    if a[i] > a[i+1]:
        if a[i+1] == -1:
#             a[i+1] = a[i+2]
            # if a[i] > a[i+1]
            # if a[i+1] == -1
            mix = a[i]
            continue
        else:
            a[i], a[i+1] = a[i+1], a[i]


In [26]:
a_t = np.zeros(len(a))

In [8]:
# sorts the elements in array if i > 0
a_s = sorted([i for i in a if i>0])
a_s

[150, 160, 170, 180, 190]

In [10]:
# enumerate exposes the indices of the elements in array a:
# once we have the indices, we can use them to insert in specific places
# in the original array
for n, i in enumerate(a):
    if i == -1:
        a_s.insert(n, i)
        

In [6]:
a_s

[-1, 150, 160, 170, -1, -1, 180, 190]

In [9]:
for n, i in enumerate(a):
    print(n,i)

0 -1
1 150
2 190
3 170
4 -1
5 -1
6 160
7 180


# InputStrings Changing

- Remove '()' from strings and return the strings reversed

In [ ]:
def find_paran(input_s):
    para = input_s.find('(')
    para2 = input_s.find('(')
    # get the word from the string:
    word = input_s[para+1:para2]
    # check for another parantheses in the word:
    para_w = word.find('(')

In [65]:
para_w = second.find('(')
# para_w = third.find('()')
# para_w
if para_w != -1:
#     print(para_w)
    # that means the word contains another string:
    # so slice the word using the string:
    para2_w = second.find(')')
    word_2 = second[para_w+1:para2_w]
    print(word_2)

ba


In [29]:
for n, i in enumerate(input_s):
#     print(n,i)
    word = input_s[para:para2]

In [66]:
para = input_s.find('(')
para2 = input_s.find(')')

In [72]:
first=input_s[:para]
second=input_s[para+1:para2+2]
third=input_s[para2+2:]
first,second,third

('foo', 'bar(baz))', 'blim')

In [39]:
second = second[::-1]
second

'rab'

In [40]:
return_s = first+second+third
return_s

'Foorabzad'

In [44]:
word = input_s[para+1:para2]

In [43]:
word

'(bar'

In [32]:
word[::-1]

'rab'

In [51]:
type_brackets = ['()', '{}', '[]']
while any(x in input_s for x in type_brackets):
    print(x)

In [52]:
input_s = 'foo(bar(baz))blim'
p_s = input_s.find('(')
p_s

3

In [88]:
input_s = 'foo(bar(baz))blim'

In [96]:
for n,i in enumerate(input_s):
    print(n,i)

0 f
1 o
2 o
3 (
4 b
5 a
6 r
7 (
8 b
9 a
10 z
11 )
12 )
13 b
14 l
15 i
16 m


In [104]:
'''
Find the brackets and the string in-between
'''
def subs(str_i):
    # take in the string, find the ( ) and then resolve the issue:
    i = str_i.find('(')
    # slice it
    substr = str_i[i+1:]
    print(substr)
    x = substr.find('(')
    if x != -1:
        # we need to find the substring:
        substr2 = substr[x+1:]
        print('substr2:', substr2)
        x_2 = substr2.find(')')
        print(x_2)
        substr_2 = substr2[:x_2]
        print('substr2:', substr2)
        # reverse teh substr2
        substr_2 = substr_2[::-1]
        
        #rest half:
        sub_2 = substr2[x_2+1:]
        
        print('sub_2:', sub_2)
    if x == -1:
        # work with substr
        i_2 = substr.find(')')
        sub = substr[:i_2]
        print("Sub:", sub)
    substr_1 = substr.find(')')
    sub_str = substr[:substr_1-1]
    return sub_str

subs(input_s)

bar(baz))blim
substr2: baz))blim
3
substr2: baz))blim
sub_2: )blim


'bar(ba'

In [84]:
i = input_s.find('(')
print('i:', i)
part_s = input_s[i+1:]
print('part_s:', part_s)
# check if the part string has another (

x = part_s.find('(')
print('x:', x)
if x == -1:
    # find the first closing bracket
    i_2 = part_s.find(')')
    subs_1 = part_s[i+1:i_2-1]
    subs_1_i = subs_1[::-1]
    first = input_s[:i-1]
    second = input_s[i_2+1:]
elif x != -1:
    ppart_s = part_s[x+1:]
    # then find the next closing parentheses
    x_2 = ppart_s.find(')')
    
    subs_2 = ppart_s[:x_2-1]
    subs_2_i = subs_2[::-1]
    # after reversing the second string, we combine it with the first half part:
subs_ = subs_1+subs_2_i 
subs_ = subs[::-1]
return_s = first+subs_+second

i: 3
part_s: bar(baz))zad
x: 3


NameError: name 'subs_1' is not defined

In [75]:
def reverseInParentheses(input_s):
    # slice the string using the parantheses as the guidance. 
    # 
    i = input_s.find('(')
    part_s = input_s[i+1:]
    # check if the part string has another (
    x = part_s.find('(')
    if x == -1:
        i_2 = part_s.find(')')
        subs_1 = part_s[x+1:x-1]
        subs_1_i = subs_1[::-1]
        first = input_s[:i-1]
        second = input_s[i_2+1:]
    elif x != -1:
        ppart_s = part_s[x+1:]
        # then find the next closing parentheses
        x_2 = ppart_s.find(')')
        subs_2 = ppart_s[:x_2-1]
        subs_2_i = subs_2[::-1]
        # after reversing the second string, we combine it with the first half part:
    subs_ = subs_1+subs_2_i 
    subs_ = subs[::-1]
    return_s = first+subs_+second
    # first = 
    # second = 
    # third = 
    return return_s

In [111]:
def reverseStr(s):
    for i in range(len(s)):
        if s[i] == '(':
            start = i
        if s[i] == ')':
            end = i 

            return reverseStr(s[:start] + s[start+1:end][::-1] + s[end+1:])
    
    return s

In [112]:
reverseStr(input_s)

'foobazrabblim'

# AlternatingSums

In [38]:
a = [50, 60, 60, 45, 70]

In [27]:
team_1 = []
team_2 = []

In [28]:
for i,x in enumerate(a):
#     team_1.append(x)
#     print(i)
    # append 0 to team 1 and append 2 to team 2
    team_1.append(x)

In [43]:
tots = []
tots2 = []
# for i, x in enumerate(a):
#     tots += x
#     i += 1
#     tots2 += x

In [45]:
for i,x in enumerate(a):
    if i%2 == 0:
        tots.append(x)
    elif i%2 != 0:
        tots2.append(x)
    
tots, tots2

([50, 60, 70], [60, 45])

In [46]:
sum(a[::2]),sum(a[1::2])

(180, 105)

In [47]:
a[::2]

[50, 60, 70]

In [48]:
a[1::2]

[60, 45]

In [49]:
a[::3]

[50, 45]

In [57]:
s = 'ElonMuskyiscoooool'
s[::5]

'Euso'

In [62]:
len_i = 3
ast = '*' * (len_i+2)
ast

'*****'

In [79]:
picture = ["abc",
           "ded"]

In [81]:
picture

['*****', '*abc*', '*ded*', '*****']

In [80]:
len_i = len(picture[0])
for i in range(len(picture)):
    # add a string of ** equal to the number of first element + ***
    picture[i] = '*' + picture[i] + '*'
    

print(len_i)
ast = '*' * (len_i+2)
print(ast)
# also add asteriks to the string:
picture.insert(0, ast)
picture.insert(len(picture), ast)
    


    

3
*****


In [67]:
# go to the first index, add it to one lsit
# go to the second index and add to the second:

tots = [x for i,x in enumerate(a)]

In [41]:
tots

[50, 60, 60, 45, 70]

In [29]:
team_1, team_2

([50, 60, 60, 45, 70], [])

In [15]:
for i in range(len(a)):
    print(a[i])
    i += 1
    print(a[i])

50
60
60
60
60
45
45
70
70


IndexError: list index out of range

In [12]:
for i in range(len(a)):
    team_1.append(a[i])
    i+1
    team_2.append(a[i])

In [17]:
team_1, team_2

([50, 60, 60, 45, 70, 0, 1, 2, 3, 4], [50, 60, 60, 45, 70, 1, 2, 3, 4, 5])

## areSimilar 

Two arrays are called similar if one can be obtained from another by swapping at most one pair of elements in one of the arrays.

Given two arrays a and b, check whether they are similar.

In [94]:
# should we do count of elements?
# the counts should be the same otherwise it is not 
a = [1, 2, 3]
b = [3, 5, 1]

In [95]:
set(a)

{1, 2, 3}

In [100]:
def isSimilar(a, b):
    '''
    for i in b:
        if i in set(a):
            return True
        else:
            return False
    '''
    for i in set(a):
        for i in set(b):
            if a.count(i) == b.count(i):
                return True
            else:
                return False
    
    
    
isSimilar(a, b)

True

In [98]:
for i in set(a):
    for i in set(b):
        if a.count(i) == b.count(i):
            return True
        else:
            return False
#     print(a.count(i))

SyntaxError: 'return' outside function (<ipython-input-98-8ecb4ac9b94b>, line 4)

In [107]:
a = [1, 2, 2]
b =[2, 1, 1]

In [2]:
a = [1, 3, 2]
b = [1, 2, 3]

# for i in set(a):
#     print(a.count(i))
#     print(b.count(i))
    

In [4]:
# a = [1, 2, 2]
# b = [2, 1, 1]
# # print(set(a))
# print(set(b))
n = len(a)
m = len(b)

a.sort()
b.sort()

for i in range(0, n):
     if a[i] != b[i]:
        print(False)
print(True)

True


In [ ]:
i = 0
while a:
    a.count(i)
    i += 1
    print(a.count(i))

In [51]:

A= [832, 998, 148, 570, 533, 561, 894, 147, 455, 279]
B= [832, 998, 148, 570, 533, 561, 455, 147, 894, 279]
    

In [55]:
if sorted(A) == sorted(B) and sum([a!=b for a,b in zip(A,B)])<=2:
    print(True)
else:
    print(False)

False


In [54]:
A= [832, 998, 148, 570, 533, 561, 894, 147, 455, 279]
B= [832, 570, 148, 998, 533, 561, 455, 147, 894, 279]

In [52]:
sorted(A)

[147, 148, 279, 455, 533, 561, 570, 832, 894, 998]

In [53]:
sorted(B)

[147, 148, 279, 455, 533, 561, 570, 832, 894, 998]

In [10]:
set_a = set(a)
set_a

{147, 148, 279, 455, 533, 561, 570, 832, 894, 998}

In [48]:
A = [1, 2, 1]
B = [2, 2, 1]

In [44]:
sum([a!=b for a,b in zip(A,B)])

1

In [23]:
a.count()

TypeError: count() takes exactly one argument (0 given)

In [25]:
def simi(a,b):
    n = len(a)
    m = len(b)
    misc = []
    for i in range(0, n):
        if a.count(i) > 1 or b.count(i) > 1:
            return False
        if a[i] != b[i]:
            misc.append(a[i])
        
    if len(misc) > 2:
        return False
    else:
        return True

In [29]:
for a,b in zip(a,b):
    if sum(a!=b) > 2:
        print(False)

TypeError: 'int' object is not iterable

In [37]:
l_c = [a!=b for a,b in zip(a,b)]
l_c

[True, False, False]

In [38]:
sum(l_c)

1

In [35]:
if sum(l_c) >= 2:
    print('False')

In [26]:
simi(a,b)

False

In [22]:
n = len(a)
m = len(b)
misc = []
for i in range(0, n):
#     if b[i] not in a:
#         print(False)
    if a.count(i) > 1:
        return False
    if a[i] != b[i] and b[i] not in set(a):
        misc.append(b[i])
# check if the elements in b[i] even exist in the 
print(misc)

[]


In [12]:
if len(misc) > 2:
    printFalse

In [14]:
a= [2, 3, 9]
b= [10, 3, 2]

In [ ]:
a = [1, 1, 1]
c = 0
# what to do to make 
# make the difference with 
for i in a:
    if a[i] > a[i+1]:
        

In [120]:
a = [13, 1, 1]

In [121]:
diff = []
for i in range(len(a)-1):

    # find difference:
    c = 1
    if a[i] >= a[i+1]:
        d = a[i] - a[i+1]
#         diff.append(d)
#         print(diff)
        a[i+1] = a[i+1] + d + 1
        diff.append(d+1)
        print(diff)
#         print(a[i+1])
#         print(diff)

[13]
[13, 14]


In [122]:
diff

[13, 14]

In [123]:
a

[13, 14, 15]

In [125]:
sum(diff)

27

In [139]:
str_i = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbccccaaaaaaaaaaaaa'
nums = []
for i in str_i:
    x = (str_i.count(i))
    nums.append(x)
print(nums)

[43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 3, 3, 3, 4, 4, 4, 4, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43]


In [142]:
str_i = 'orattro'
nums = []
count = 0
for i in str_i:
    nums.append(str_i.count(i))
    
    if str_i.count(i) == 1:
        count += 1
# if count > 1:
#     return False
# else:
#     return True

# Rotator

In [146]:
nums = []
for i in str_i:
    nums.append(str_i.count(i))
print(nums)
# for i in nums:
    

[2, 2, 1, 2, 2, 2, 2]


In [140]:
def palindromeRearranging(str_i):
    nums = []
    count = 0
    c = 0
    if len(str_i) == 1:
        return True
    for i in str_i:
        if str_i.count(i) == 1:
            count += 1
        elif str_i.count(i) % 2 != 0:
            c += 1

    if count >= 1 and c >= 1:
        return False
    if c> 1:
        return False
    if count > 1:
        return False
    else:
        return True

In [147]:
str_i = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbccccaaaaaaaaaaaaa'

In [143]:
nums = []
for i in set(str_i):
    nums.append(str_i.count(i)%2)
print(sum(nums))

1


In [148]:
palindromeRearranging(str_i)

False

In [144]:
def palin(inputString):
    return sum([inputString.count(i)%2 for i in set(inputString)]) <=1

In [149]:
palin(str_i)

False

In [130]:
nums

[2, 2, 1, 2, 2, 2, 2]

## Maximal Adjacent DIfference


In [3]:
# can we find differences between elements as a list comprehension.
a = [2, 4, 1, 0]

d = max([abs(a[i]-a[i+1]) for i in range(len(a)-1)])
d

3

In [33]:
inputString = "172.16.254.1a"
# sp_str = inputString.split('.')
# sp_str

In [22]:
def isIPv4Address(inputString):
    sp_str = inputString.split('.')
    if sp_str[0] == '':
        return False 
    for i in sp_str:
        if int(i) != 
        if int(i) >= 0 and int(i) <=255:
            return True 

isIPv4Address(inputString)

True

In [16]:
len(sp_str)

4

In [24]:
int('1a')

ValueError: invalid literal for int() with base 10: '1a'

In [17]:
if sp_str[0] == '':
    print(False)
for i in sp_str:
    if int(i) >= 0 and int(i) <= 255:
        print(False)

False


ValueError: invalid literal for int() with base 10: ''

In [58]:
inputString = "172.16.254.1"

In [63]:
inputString= "172.16.254.1"

In [91]:
inputString = "0.254.255.0a"

In [95]:
inputString = "172.316.254.1"

In [109]:
sp_str = ['64', '233', '161', '00']

In [110]:
inputString= "64.233.161.00"

### MyAnswer

In [144]:

def count(lst):
    return sum(bool(x) for x in lst)
def isIPv4Address(inputString):
    sp_str = inputString.split('.')
    print('sp_str:', sp_str)
    if sp_str[0] == '':
        return False
    t_f = []
    for i in sp_str:
        if i.isdigit():
            print('is_digit:', i)
            if i == '01' or i == '00':
                return False 
            if i[0] == '0':
                return False
            if int(i) >= 0 and int(i) <=255:
                t_f.append(True)
                print('t_f:', t_f)
            else:
                t_f.append(False)

    print(t_f)
    print('sum', count(t_f))
    sum_l = count(t_f)
    if sum_l != len(sp_str):
        return False
    else:
        return True

In [141]:
string = '3232.3232.32'

In [142]:
def check(arr):
    p = arr.split('.')
    return len(p) >=2 and all(n.isdigit() and int(n) %32 == 0 for n in p)

In [143]:
check(string)

True

In [124]:
int('01')

1

In [125]:
isIPv4Address(inputString)

sp_str: ['64', '233', '161', '00']
is_digit: 64
t_f: [True]
is_digit: 233
t_f: [True, True]
is_digit: 161
t_f: [True, True, True]
is_digit: 00


False

### Efficient solution:

In [145]:
def isIPv4Address(arr):
    p = arr.split('.')
    return len(p) == 4 and all(n.isdigit() and 0 <= int(n) <256 for n in p)


# Biggest jumps

In [28]:
inputArray = [5, 3, 6, 7, 9]


In [29]:
def aO(arr):
    # sort the array first
    d = []
    arr = sorted(arr)
    for i in range(len(sorted(arr))-1):
        print(arr)
        dis = arr[i+1] - arr[i]
        if dis > 1:
            d.append(dis)
    return d

In [30]:
aO(inputArray)

[3, 5, 6, 7, 9]
[3, 5, 6, 7, 9]
[3, 5, 6, 7, 9]
[3, 5, 6, 7, 9]


[2, 2]

# Important Python Concepts

 ### 1. Set()
Python sets are used to store multiple items in a single variable. For example, if we wanted to get a count of variables in the set, instead of doing:
```
for i in a:
    print(count(i))
```
We can do:

In [146]:
a = ['b', 'a', 's', 'o','s', 'a']

In [149]:
l = [a.count(i) for i in set(a)]
l

[1, 2, 1, 2]

### 2. Enumerate()

While working with arrays where you might need to insert in a specific index location, it is very helpful to enumerate arrays that provide with 2 columns, one with indices and the other with values.
WE can do so:

```
for a, b in enumerate(a):
    print(a,b)
    
```

In [151]:
for a,b in enumerate(a):
    print(a,b )

0 b
1 a
2 s
3 o
4 s
5 a


### Example:

Some people are standing in a row in a park. There are trees between them which cannot be moved. Your task is to rearrange the people by their heights in a non-descending order without moving the trees. People can be very tall!

Example

For a = [-1, 150, 190, 170, -1, -1, 160, 180], the output should be
sortByHeight(a) = [-1, 150, 160, 170, -1, -1, 180, 190].


In [152]:

def sortByHeight(a):
    # we can do another array that is the same length as the original one and replace the 0s with 
    a_s = sorted([i for i in a if i>0])
    for n, i in enumerate(a):
        if i ==-1:
            a_s.insert(n, i)
    return a_s
