## Matrix CodeSignal

In [1]:
import numpy as np
import math

In [38]:
image = [[1, 0, 1], 
         [0, 1, 1], 
         [1, 1, 1]]

In [43]:
if len(image[0]) == 3 and len(image[1]) == 3:
        print(math.floor(np.sum(image)/9))

1


In [22]:
image2 = np.array([[7, 4, 0, 1], 
         [5, 6, 2, 2], 
         [6, 10, 7, 8], 
         [1, 4, 2, 0]])

In [44]:
mat = [[36,0,18,9], 
 [27,54,9,0], 
 [81,63,72,45]]

In [45]:
len(mat[0])

4

In [49]:
len(mat[0])

4

In [50]:
len(mat)

3

In [36]:
mat = [[27,0,54,9,0,63,90], 
 [81,63,72,45,18,27,0], 
 [0,0,9,81,27,18,45], 
 [45,45,27,27,90,81,72], 
 [45,18,9,0,9,18,45], 
 [27,81,36,63,63,72,81]]

In [54]:
len(mat[0])

7

In [35]:
def boxBlur(m):
    r = len(m)
    c = len(m[0])
    ans = []
    for i in range(1,r-1):
        row=[]
        for j in range(1,c-1):
            row.append(sum([m[i+k][j+l] for k in [-1,0,1] for l in [-1,0,1]])//9)
            print(row)
        ans.append(row)
        print(ans)
        
    return ans

In [38]:
boxBlur(mat)

[34]
[34, 37]
[34, 37, 35]
[34, 37, 35, 32]
[34, 37, 35, 32, 32]
[[34, 37, 35, 32, 32]]
[38]
[38, 41]
[38, 41, 44]
[38, 41, 44, 46]
[38, 41, 44, 46, 42]
[[34, 37, 35, 32, 32], [38, 41, 44, 46, 42]]
[22]
[22, 24]
[22, 24, 31]
[22, 24, 31, 39]
[22, 24, 31, 39, 45]
[[34, 37, 35, 32, 32], [38, 41, 44, 46, 42], [22, 24, 31, 39, 45]]
[37]
[37, 34]
[37, 34, 36]
[37, 34, 36, 47]
[37, 34, 36, 47, 59]
[[34, 37, 35, 32, 32], [38, 41, 44, 46, 42], [22, 24, 31, 39, 45], [37, 34, 36, 47, 59]]


[[34, 37, 35, 32, 32],
 [38, 41, 44, 46, 42],
 [22, 24, 31, 39, 45],
 [37, 34, 36, 47, 59]]

In [17]:
z = []
for i in range(len(image2[0])):
    for k in range(len(image2)):
#         print(image2[k][i])
        # how to limit the number of elements we get?
        # we can use break? 
        z.append(image2[k][i])
        if len(z) == 3:
            break
        else:
            continue

print(z)

[7, 5, 6, 4, 6, 10, 4, 0, 2, 7, 2, 1, 2, 8, 0]


In [35]:
b1 = image2[:3, :3]
b2 = image2[:3, 1:4]
b3 = image2[1:4, :3]
b4 = image2[1:4, 1:4]

In [36]:
b1, b2, b3, b4

(array([[ 7,  4,  0],
        [ 5,  6,  2],
        [ 6, 10,  7]]),
 array([[ 4,  0,  1],
        [ 6,  2,  2],
        [10,  7,  8]]),
 array([[ 5,  6,  2],
        [ 6, 10,  7],
        [ 1,  4,  2]]),
 array([[ 6,  2,  2],
        [10,  7,  8],
        [ 4,  2,  0]]))

In [37]:
b1 = round(np.sum(b1)/9)
b1


5

In [4]:
image2

[[7, 4, 0, 1], [5, 6, 2, 2], [6, 10, 7, 8], [1, 4, 2, 0]]

In [5]:
len(image2)

4

In [10]:
a = 0
z = 3
k = 0
for i in range(3):
    k += sum(image2[i][a:z])


In [11]:
# Cut the matrix into sub lists and use those to get average and sum.
k

47

In [3]:
rand = np.zeros([3, 3])
rand

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
rand.shape[0]

3

In [4]:
mat = [[7, 4, 0, 1], 
         [5, 6, 2, 2], 
         [6, 10, 7, 8], 
         [1, 4, 2, 0]]

In [10]:
len(mat)

4

In [8]:
a1 = 0
for i in range(3):
    a = mat[i][:3]
    a1 += sum(a)
    

In [9]:
a1

47

In [ ]:
# for the second round, we want both the index for columns to increase by 1.


# More Matrices

In [74]:
matrix = [['true', 'false', 'false'],
          ['false', 'true', 'false'],
          ['false', 'false', 'false']]

In [78]:
matrix = [[true, false, false],
          [false, true, false],
          [false, false, false]]

NameError: name 'true' is not defined

In [79]:
def minesweeper(matrix):

    r = []
    
    for i in range(len(matrix)):
        r.append([])
        for j in range(len(matrix[0])):
            l = -matrix[i][j]
            print("l:", l)
            for x in [-1,0,1]:
                for y in [-1,0,1]:
                    if 0<=i+x<len(matrix) and 0<=j+y<len(matrix[0]):
                        l += matrix[i+x][j+y]

            r[i].append(l)
    return r
                    

In [77]:
minesweeper(matrix)

TypeError: bad operand type for unary -: 'str'

In [64]:
mat2 = np.zeros((matrix.shape[0], matrix.shape[1]))

In [66]:
mat2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [67]:
r = len(matrix)
c = len(matrix[0])

In [73]:
count = 0
for i in range(0, r-1):
    for j in range(0, c-1):
        print(matrix[i][j])
        if matrix[i][j+1] == 'true':
            count += 1
        # get the neighbors:
        print(sum([matrix[i+z][j+k] for z in [-1,0,1] for k in [-1,0,1]]))

true


TypeError: unsupported operand type(s) for +: 'int' and 'numpy.str_'

In [72]:
count

1

In [20]:
for i in range(0, len(matrix[0])-1):
    count = 0
    for j in range(0, len(matrix)-1):
        print(matrix[i][j])
        if matrix[i][j+1] == 'true':
            count += 1
        elif matrix[i+1][j] == 'true':
            count _
count

true
false
false
true


1

In [ ]:
for i in range(1, len(matrix[0])):
    count = 0
    for j in range(1, len(matrix)):
        for k in [-1, 0, 1]:
            

In [14]:
# every element which is directly next to a true, we get a +1
#  

for i in range(1, len(matrix[0])):
    count = 0
    for j in range(1, len(matrix)):
        for k in [-1, 0, 1]:
            for z in [-1, 0, 1]:
#                 if matrix[i+k][j+z] == 'true':
#                     count += 1
#                 else:
#                     continue
                print(matrix[i+k][j+z])

true
false
false
false
true
false
false
false
false
false
false


IndexError: list index out of range

In [61]:
# use recursion, by going through the whole array, 

def boxBlur(m):
    r = len(m)
    c = len(m[0])
    ans = []
    for i in range(1,r-1):
        row=[]
        for j in range(1,c-1):
            row.append(sum([m[i+k][j+l] for k in [-1,0,1] for l in [-1,0,1]])//9)
            print(row)
        ans.append(row)
        print(ans)
        
    return ans

In [62]:
mat2 = np.zeros((matrix.shape[0], matrix.shape[1]))

In [59]:
rowd = {}
for i in range(1, len(matrix[0])-1):
    count = 0
    ans = []
    for j in range(1, len(matrix)-1):
        row = []
        for z in [-1,0,1]:
            for k in [-1,0,1]:
                if matrix[i+z][j+k] == 0:
                    count = 0
                    mat2[i+z][j+k].replace(matrix[i+z][j+k])
#                 rowd[matrix[i][j]] = row.append(([matrix[i+z][j+k]]))
#                 print(row)
#                 print(rowd)

In [60]:
mat2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
def neighbors(radius, rowNumber, columnNumber):
     return [[a[i][j] if  i >= 0 and i < len(a) and j >= 0 and j < len(a[0]) else 0
                for j in range(columnNumber-1-radius, columnNumber+radius)]
                    for i in range(rowNumber-1-radius, rowNumber+radius)]

In [ ]:
# check for the true and false values and update the value in the matrix.

In [2]:
image = [[1, 0, 1], 
         [0, 1, 1], 
         [1, 1, 1]]

In [7]:
r = []
for i in range(len(image)):
    r.append([])
    for j in range(len(image[0])):
        k = image[i][j]
        l = -image[i][j]
        print("l", l)
        print("k", k)

l -1
k 1
l 0
k 0
l -1
k 1
l 0
k 0
l -1
k 1
l -1
k 1
l -1
k 1
l -1
k 1
l -1
k 1


In [10]:
matrix = [[True, False, False],
          [False, True, False],
          [False, False, False]]

In [15]:
r = []
for i in range(len(matrix)):
    r.append([])
    for j in range(len(matrix[0])):
#         k = matrix[i][j]
        l = -matrix[i][j]
        print("l", l)
#         for x in [-1,0,1]:
#             for y in [-1,0, 1]:
                
#         print("k", k)


l -1
l 0
l 0
l 0
l -1
l 0
l 0
l 0
l 0


In [17]:
x = False
y = -x
y

0

In [1]:
arra = [1, 2, 1]
org = 1
rep = 3

In [19]:
for a,i in enumerate(arra):
    if i == org:
        arra[a] = rep

1
1


In [23]:
n = 2436
s = str(n).split()
d = [int(d) for d in str(n)]

In [24]:
for d in str(n):
    if d % 2 == 0:
        return True

[2, 4, 3, 6]

In [41]:
def evenDigitsOnly(n):
    # string split:
    # s = str(n)
    for d in str(n):
#         print(d)
        if int(d) % 2 == 0:
            continue
        else:
            return False

In [76]:
n = '2436a-'

In [78]:
n[0]

'2'

In [63]:
corr = [str(), _, int()]

In [79]:
if n[0].isnumeric():
    print(False)

False


In [73]:
for i in n:
#     print(type(i))
    print(i)
    if i.isalpha() or i.isnumeric() or i == '-':
        continue
    else:
        print('False')
print('True')

2
4
3
6
a
-
True


In [53]:
matched_list = [type(characters) in corr for characters in s]
matched_list

[False, False, False, False, False, False, False, False, False, False, False]

In [46]:
for i in s:
    print(i)

v
a
r
_
_
1
_
_
i
n
t


In [45]:
s = 'var__1__int'

for i in s:
    for k in corr:
        if i == k:
            continue
        else:
            print(False)

False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False


In [42]:
n = 2346
evenDigitsOnly(n)

False

In [20]:
arra

[3, 2, 3]

# Working with Strings

In [81]:
import string

string.ascii_lowercase

'abcdefghijklmnopqrstuvwxyz'

In [88]:
a_dict = {}
for i in range(len(string.ascii_lowercase)-1):
    print(i)
    a_dict[string.ascii_lowercase[i]] = string.ascii_lowercase[i+1]
    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [140]:
a_dict

{'a': 'b',
 'b': 'c',
 'c': 'd',
 'd': 'e',
 'e': 'f',
 'f': 'g',
 'g': 'h',
 'h': 'i',
 'i': 'j',
 'j': 'k',
 'k': 'l',
 'l': 'm',
 'm': 'n',
 'n': 'o',
 'o': 'p',
 'p': 'q',
 'q': 'r',
 'r': 's',
 's': 't',
 't': 'u',
 'u': 'v',
 'v': 'w',
 'w': 'x',
 'x': 'y',
 'y': 'z'}

In [161]:
# ret = ''
for i in inputString:
#     print(i)
    print("i:", i)
    print("dict_i:", a_dict[i])
    ret = inputString.replace(i, a_dict[i])
#     ret = inputString[i].replace(inputString[i], a_dict[inputString[i]])

i: a
dict_i: b
i: b
dict_i: c
i: c
dict_i: d


In [163]:
a_dict['z'] = 'a'
a_dict

{'a': 'b',
 'b': 'c',
 'c': 'd',
 'd': 'e',
 'e': 'f',
 'f': 'g',
 'g': 'h',
 'h': 'i',
 'i': 'j',
 'j': 'k',
 'k': 'l',
 'l': 'm',
 'm': 'n',
 'n': 'o',
 'o': 'p',
 'p': 'q',
 'q': 'r',
 'r': 's',
 's': 't',
 't': 'u',
 'u': 'v',
 'v': 'w',
 'w': 'x',
 'x': 'y',
 'y': 'z',
 'z': 'a'}

In [162]:
ret

'abd'

In [196]:
i = 'a'
i = i.replace(i, a_dict[i])
i

'b'

In [203]:
new_str = ''
for i in inputString:
    new_str += str(i.replace(i, a_dict[i], len(inputString)))
print(new_str)

bcd


In [198]:
for i in inputString:
    ret = i.replace(i, a_dict[i])

In [192]:
inputString = 'abc'

In [197]:
for i in range(len(inputString)):
#     print(inputString[i])
    ret = i.replace(i, a_dict[i], len(inputString))

AttributeError: 'int' object has no attribute 'replace'

In [199]:
ret

'd'

In [146]:
i = '43'
for a in i:
    i.replace(a, '5', 2)
i

'43'

In [143]:
inputString

'abc'

In [141]:
inputString = 'abc'

In [116]:
for a,i in enumerate(inputString):
#     print(a, i)
    list1 = list(inputString)
#     print(list1[a])
    list1[a] = a_dict[inputString[a]]
    

In [124]:
for a,i in enumerate(inputString):
    print(i)
    

a
b
c


In [117]:
print(list1)

['a', 'b', 'd']


In [104]:
for a,i in enumerate(inputString):
#     print(a_dict[inputString[a]])
    print(inputString[a])
    inputString[a] = a_dict[inputString[a]]
    

a


TypeError: 'str' object does not support item assignment

In [118]:
a_dict

{'a': 'b',
 'b': 'c',
 'c': 'd',
 'd': 'e',
 'e': 'f',
 'f': 'g',
 'g': 'h',
 'h': 'i',
 'i': 'j',
 'j': 'k',
 'k': 'l',
 'l': 'm',
 'm': 'n',
 'n': 'o',
 'o': 'p',
 'p': 'q',
 'q': 'r',
 'r': 's',
 's': 't',
 't': 'u',
 'u': 'v',
 'v': 'w',
 'w': 'x',
 'x': 'y',
 'y': 'z'}

## ChessBoard

In [204]:
def chessBoardCellColor(cell1, cell2):
    # if cell is on a, c, e and g:
    f = cell1[0]
    n = cell1[1]
    s = cell2[0]
    m = cell2[1]
    cell1_n = ''
    cell2_n = ''
    if f == 'a' or f =='c' or f=='e' or f=='g':
        if n % 2 != 0:
            cell1_n = 'dark'
    if s == 'b' or s=='e' or s=='f' or s =='h':
        if m % 2 == 0:
            cell2_n = 'dark'
    print('cell2_n', cell2_n)
    if cell1_n == cell2_n:
        return True
    else:
        return False
    

In [214]:
cell1 = 'A1'
cell2 = 'H2'
f = cell1[0].lower()
n = int(cell1[1])
s = cell2[0].lower()
m = int(cell2[1])
print('f:{}, n:{}, s:{}, m:{}'.format(f,n,s,m))

# cell1_n = ''
# cell2_n = ''

if f == 'a' or f =='c' or f=='e' or f=='g':
    if n % 2 != 0:
        cell1_n = 'dark'
if s == 'b' or s=='e' or s=='f' or s =='h':
    if m % 2 == 0:
        cell2_n = 'dark'
# print(cell1_n)
# print(cell2_n)
# print('cell2_n', cell2_n)
if cell1_n == cell2_n:
    print(True)
else:
    print(False)

f:a, n:1, s:h, m:2
dark
dark
True


In [215]:
def chessBoardCellColor(cell1, cell2):
    
    return (ord(cell1[0])+int(cell1[1])+ord(cell2[0])+int(cell2[1]))%2==0